#DOS TIPOS DE ARCHIVOS
#ARCHIVOS DE TEXTO Y ARCHIVOS BINARIOS
# CON LOS ARCHIVOS SE PUEDE HACER 4 OPERACIONES BASICAS: 
# 1. ABRIR ARCHIVO(EN MODO LECTURA, MODO ESCRITURA) 
# 2. CERRAR ARCHIVOS
# 3.  