#COLECCIONES EN PY : SON ELEMENTOS, QUE A DIFERENCIA DE LAS VARIABLES, SON ELEMENTOS QUE CONTIENEN UN CONJUNTO DE VALOR. 



#COLECCION LIST (ARRAY EN JAVA) - SIEMPRE ENTRE CORCHETES - PUEDEN CONTENER CUALQUIER COSA
Lista = [] #UNA FORMA DE HACERLA
lista = list () #SEGUNDA FORMA DE HACERLO
list.append() #AGREGAR UN DATO A UNA LISTA (SOLO DE UNO EN UNO)
list.pop() #ELIMINA EL ULTIMO ELEMENTO DE UNA LISTA
list.count() #TE DICE CUANTOS DATOS ESTÁN REPETIDOS EN UNA LISTA (Y DENTRO DEL PARENTESIS SE PONE EL CARACTER O NUMERO QUE QUIERES SABER CUÁNTO SE REPITE)
sum(list) #SUMA LOS NUMEROS DE LA LISTA
max(list) #EL MAXIMO NUMERO DE UNA LISTA
min(list) #EL MINIMO NUMERO DE UNA LISTA


#COLECCION SET



