#TUPLAS ES UNA LISTA INMUTABLES (NO SE PUEDE MODIFICAR)
#LA TUPLA ES MAS RÁPIDA EN EJECUCION DE PROGRAMA, OCUPA MENOS ESPACIO EN MEMORIA


mitupla = ("Juan", 13, 1, 1995) #SINTAXIS - SIEMPRE ENTRE PARENTESIS
milista = list(mitupla) #METODO LIST - ESTO SE HACE PARA CONVERTIR UNA TUPLA A UNA LISTA Y ASI PODER MODIFICAR
print(mitupla[2]) #PARA BUSCAR UN ELEMENTO DE LA TUPLA
print(milista) #IMPRIME LA LISTA, QUE ANTES ERA TUPLA,QUE HEMOS CAMBIADO ANTERIORMENTE
mitupla=tuple(milista) #TUPLE PARA CONVERTIR UNA LISTA A UNA TUPLA
print(mitupla)
print("Juan" in mitupla) #IN PARA SABER SI UN ELEMENTO ESTÁ EN LALISTA MEDIANTE TRUE O FALSE

print(mitupla.count(13)) #COUNT PARA SABER CUANTOS ELEMENTOS SE REPITE LO QUE ESTÁ DENTRO DEL PARENTESIS
print(len(mitupla)) #LEN NOS DA CUANTOS ELEMENTOS TIENE LA TUPLA, NO CUANTOS INDICES.

#mitupla=("Juan",) #SINTAXIS DE UNA TUPLA UNITARIA. PONIENDO UNA COMA DETRAS DEL PRIMER ELEMENTO

