def opcionales (oblig_1, oblig_2, opc_1="uno", opc_2="dos", *args, **kwargs):  #PRIMERO PARAMETROS OBLIGATORIOS, LUEGO OPCIONALES, LUEGO PARAMETROS CON ASTERISCOS Y POR ULTIMO EL DOBLE ASTERISCON (EL *ARGS ES UN TUPLA) Y EL **KWARGS ES CLAVE:VALOR Y SE CONVIERTE EN DICCIONARIO)
    pass


opcionales()